#!/bin/bash
export ANDROID_NDK=/Users/chenpeiwen/opt/tools/android-ndk-r10e
export ANDROID_NDK_ROOT=$ANDROID_NDK
echo $ANDROID_NDK_ROOT
PATH=$ANDROID_NDK_ROOT/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin:$PATH
echo $PATH
./Configure android-arm -D__ANDROID_API__=14
make
